services:
  bun-react-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    # Volúmenes solo si quieres editar en "hot reload" dentro del contenedor
    volumes:
      - .:/app
      - /app/node_modules
