export const hornetAnimations = {
    evade: [
      '/Hornet/Hornet Cln_evade0000.png',
      '/Hornet/Hornet Cln_evade0001.png',
      '/Hornet/Hornet Cln_evade0002.png',
      '/Hornet/Hornet Cln_evade0003.png',
      '/Hornet/Hornet Cln_evade0004.png',
      '/Hornet/Hornet Cln_evade0005.png',
    ],
    hard_land: [
      '/Hornet/Hornet Cln_hard_land0000.png',
      '/Hornet/Hornet Cln_hard_land0001.png',
      '/Hornet/Hornet Cln_hard_land0002.png',
      '/Hornet/Hornet Cln_hard_land0003.png',
      '/Hornet/Hornet Cln_hard_land0004.png',
      '/Hornet/Hornet Cln_hard_land0005.png',
    ],
    harpoon_side: [
      '/Hornet/Hornet Cln_harpoon_side0000.png',
      '/Hornet/Hornet Cln_harpoon_side0001.png',
      '/Hornet/Hornet Cln_harpoon_side0002.png',
    ],
    harpoon_thread: [
      '/Hornet/Hornet Cln_harpoon_thread_v020000.png',
      '/Hornet/Hornet Cln_harpoon_thread_v020001.png',
      '/Hornet/Hornet Cln_harpoon_thread_v020002.png',
      '/Hornet/Hornet Cln_harpoon_thread_v020003.png',
      '/Hornet/Hornet Cln_harpoon_thread_v020004.png',
      '/Hornet/Hornet Cln_harpoon_thread_v020005.png',
      '/Hornet/Hornet Cln_harpoon_thread_v020006.png',
      '/Hornet/Hornet Cln_harpoon_thread_v020007.png',
      '/Hornet/Hornet Cln_harpoon_thread_v020008.png',
    ],
    harpoon_up: [
      '/Hornet/Hornet Cln_harpoon_up0000.png',
      '/Hornet/Hornet Cln_harpoon_up0001.png',
      '/Hornet/Hornet Cln_harpoon_up0002.png',
    ],
    hornet_beast_npc_version: [
      '/Hornet/Hornet Cln_Hornet_Beast_NPC_Version0000.png',
      '/Hornet/Hornet Cln_Hornet_Beast_NPC_Version0001.png',
      '/Hornet/Hornet Cln_Hornet_Beast_NPC_Version0002.png',
      '/Hornet/Hornet Cln_Hornet_Beast_NPC_Version0003.png',
      '/Hornet/Hornet Cln_Hornet_Beast_NPC_Version0004.png',
      '/Hornet/Hornet Cln_Hornet_Beast_NPC_Version0005.png',
      '/Hornet/Hornet Cln_Hornet_Beast_NPC_Version0006.png',
      '/Hornet/Hornet Cln_Hornet_Beast_NPC_Version0007.png',
      '/Hornet/Hornet Cln_Hornet_Beast_NPC_Version0008.png',
      '/Hornet/Hornet Cln_Hornet_Beast_NPC_Version0009.png',
      '/Hornet/Hornet Cln_Hornet_Beast_NPC_Version0010.png',
      '/Hornet/Hornet Cln_Hornet_Beast_NPC_Version0011.png',
      '/Hornet/Hornet Cln_Hornet_Beast_NPC_Version0012.png',
      '/Hornet/Hornet Cln_Hornet_Beast_NPC_Version0013.png',
    ],
    idle_to_point: [
      '/Hornet/Hornet Cln_idle_to_point0000.png',
      '/Hornet/Hornet Cln_idle_to_point0001.png',
      '/Hornet/Hornet Cln_idle_to_point0002.png',
      '/Hornet/Hornet Cln_idle_to_point0003.png',
      '/Hornet/Hornet Cln_idle_to_point0004.png',
      '/Hornet/Hornet Cln_idle_to_point0005.png',
      '/Hornet/Hornet Cln_idle_to_point0006.png',
      '/Hornet/Hornet Cln_idle_to_point0007.png',
    ],
    idle: [
      '/Hornet/Hornet Cln_idle0000.png',
      '/Hornet/Hornet Cln_idle0001.png',
      '/Hornet/Hornet Cln_idle0002.png',
      '/Hornet/Hornet Cln_idle0003.png',
      '/Hornet/Hornet Cln_idle0004.png',
      '/Hornet/Hornet Cln_idle0005.png',
    ],
    jump: [
      '/Hornet/Hornet Cln_jump0000.png',
      '/Hornet/Hornet Cln_jump0001.png',
      '/Hornet/Hornet Cln_jump0002.png',
      '/Hornet/Hornet Cln_jump0003.png',
      '/Hornet/Hornet Cln_jump0004.png',
      '/Hornet/Hornet Cln_jump0005.png',
      '/Hornet/Hornet Cln_jump0006.png',
      '/Hornet/Hornet Cln_jump0007.png',
      '/Hornet/Hornet Cln_jump0008.png',
      '/Hornet/Hornet Cln_jump0009.png',
    ],
    look_down: [
      '/Hornet/Hornet Cln_look_down0000.png',
      '/Hornet/Hornet Cln_look_down0001.png',
      '/Hornet/Hornet Cln_look_down0002.png',
      '/Hornet/Hornet Cln_look_down0003.png',
      '/Hornet/Hornet Cln_look_down0004.png',
      '/Hornet/Hornet Cln_look_down0005.png',
    ],
    run: [
      '/Hornet/Hornet Cln_run0000.png',
      '/Hornet/Hornet Cln_run0001.png',
      '/Hornet/Hornet Cln_run0002.png',
      '/Hornet/Hornet Cln_run0003.png',
      '/Hornet/Hornet Cln_run0004.png',
      '/Hornet/Hornet Cln_run0005.png',
      '/Hornet/Hornet Cln_run0006.png',
      '/Hornet/Hornet Cln_run0007.png',
    ],
    soft_land: [
      '/Hornet/Hornet Cln_soft_land0000.png',
      '/Hornet/Hornet Cln_soft_land0001.png',
      '/Hornet/Hornet Cln_soft_land0002.png',
    ],
    throw_side: [
      '/Hornet/Hornet Cln_throw_side0000.png',
      '/Hornet/Hornet Cln_throw_side0001.png',
      '/Hornet/Hornet Cln_throw_side0002.png',
      '/Hornet/Hornet Cln_throw_side0003.png',
      '/Hornet/Hornet Cln_throw_side0004.png',
      '/Hornet/Hornet Cln_throw_side0005.png',
      '/Hornet/Hornet Cln_throw_side0006.png',
      '/Hornet/Hornet Cln_throw_side0007.png',
      '/Hornet/Hornet Cln_throw_side0008.png',
    ],
    throw_up: [
      '/Hornet/Hornet Cln_throw_up0000.png',
      '/Hornet/Hornet Cln_throw_up0001.png',
      '/Hornet/Hornet Cln_throw_up0002.png',
      '/Hornet/Hornet Cln_throw_up0003.png',
      '/Hornet/Hornet Cln_throw_up0004.png',
      '/Hornet/Hornet Cln_throw_up0005.png',
      '/Hornet/Hornet Cln_throw_up0006.png',
      '/Hornet/Hornet Cln_throw_up0007.png',
      '/Hornet/Hornet Cln_throw_up0008.png',
    ],
    to_idle: [
      '/Hornet/Hornet Cln_to_idle0000.png',
      '/Hornet/Hornet Cln_to_idle0001.png',
      '/Hornet/Hornet Cln_to_idle0002.png',
    ],
    to_run: [
      '/Hornet/Hornet Cln_to_run0000.png',
      '/Hornet/Hornet Cln_to_run0001.png',
      '/Hornet/Hornet Cln_to_run0002.png',
      '/Hornet/Hornet Cln_to_run0003.png',
      '/Hornet/Hornet Cln_to_run0004.png',
      '/Hornet/Hornet Cln_to_run0005.png',
    ],
    turn: [
      '/Hornet/Hornet Cln_turn0000.png',
      '/Hornet/Hornet Cln_turn0001.png',
      '/Hornet/Hornet Cln_turn0002.png',
    ],
  };
  